name: Packman

on:
  push:
    branches:
      - main

jobs:
  packman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Contribution Graph
        uses: abozanona/pacman-contribution-graph@main

      - name: Display Graph
        run: |
          cat contribution-graph.svg
          echo "Generated Contribution Graph"