name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    env:
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@v2
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push pacman graph to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}